/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yy_chiprreader_utils_Algorithm */

#ifndef _Included_com_example_yy_chiprreader_utils_Algorithm
#define _Included_com_example_yy_chiprreader_utils_Algorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yy_chiprreader_utils_Algorithm
 * Method:    correlationJni
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_yy_chiprreader_utils_Algorithm_correlationJni
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     com_example_yy_chiprreader_utils_Algorithm
 * Method:    correlationJni2
 * Signature: ([S[S)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_yy_chiprreader_utils_Algorithm_correlationJni2
  (JNIEnv *, jclass, jshortArray, jshortArray);

/*
 * Class:     com_example_yy_chiprreader_utils_Algorithm
 * Method:    mixFrequenceJni
 * Signature: ([F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_yy_chiprreader_utils_Algorithm_mixFrequenceJni
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     com_example_yy_chiprreader_utils_Algorithm
 * Method:    mixAndSumJni
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_yy_chiprreader_utils_Algorithm_mixAndSumJni
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     com_example_yy_chiprreader_utils_Algorithm
 * Method:    fftJni
 * Signature: ([FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_yy_chiprreader_utils_Algorithm_fftJni
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     com_example_yy_chiprreader_utils_Algorithm
 * Method:    normolizeArrayJni
 * Signature: ([S)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_yy_chiprreader_utils_Algorithm_normolizeArrayJni
  (JNIEnv *, jclass, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
